import { Router } from 'express';
import { auth, admin } from '../middlewares/auth.js';
import * as c from '../controllers/eventController.js';
const router = Router();
router.get('/', c.list);
router.get('/published', c.published);
router.get('/featured', c.featured);
router.get('/categories', c.categories);
router.post('/bulk-delete', auth, admin, c.bulkDelete);
router.get('/:id', c.detail);
router.get('/:id/detail', c.detail);
router.get('/:id/related', c.related);
router.get('/:id/comments', c.comments);
router.post('/:id/comments', c.addComment);
router.post('/', auth, admin, c.create);
router.put('/:id', auth, admin, c.update);
router.delete('/:id', auth, admin, c.remove);
router.put('/:id/publish', auth, admin, c.publish);
router.put('/:id/unpublish', auth, admin, c.unpublish);
router.put('/:id/toggle-featured', auth, admin, c.toggleFeatured);
export default router;
